### PR TITLE
Double xaxis

### PR DESCRIPTION
**Pull request by WesleyTheGeolien**
#15

### CODE REVIEW

**Comment by kinverarity1** [comment]
Great work! I love it. However, there is a problem at my end with the version in dashwellviz. The notebook version works:

image

But the version in `_cross_over_log_norm` doesn't, at least not as it is in the PR here:

image

My testing notebook is [here](https://github.com/kinverarity1/t20-Dash_Well_Viz/blob/double_xaxis/Notebooks/PR%2020%20-%20double%20X-axis%20for%20crossover%20neutron%20density%20log.ipynb).

**Comment by WesleyTheGeolien** [comment]
Good catch @kinverarity1 I have patched the problem, the filling was happening between the wrong traces :) should be good now

**Comment by WesleyTheGeolien** [comment]
@kinverarity1 I've also added a function to add a multi xaxis plot to subplots and a demo

newplot

**Comment by kinverarity1** [comment]
Nice, thank you! Great to see the approach. There is an error:

image

Note my version of plotly; I'm hoping/assuming you have a different version? I tried to look around in `fig.layout` but I couldn't find the source code in the plotly repo and this output didn't help me much either:

```python
print(f"fig.layout.__dict__: {fig.layout.__dict__}")
axis_numbers = [key[-1] for key in fig.layout.__dict__['_validators'].keys() if 'xaxis' in key]
```

Output here: [fig.layout.txt](https://github.com/WesleyTheGeolien/t20-Dash_Well_Viz/files/4761654/fig.layout.txt)

**Comment by WesleyTheGeolien** [comment]
@kinverarity1 Ahhhh :/ il looks like it has been call `_compound_props` now rather than validators, Im pretty sure this isn't the way to go about getting the maximum axis, we should be able to get it from the number of rows and cols but trying to be cleaver

**Comment by WesleyTheGeolien** [comment]
@kinverarity1 it should be better now, I think I have found the right API call could you test it?

**Comment by kinverarity1** [comment]
Wonderful, works perfectly. Thank you.

**Comment by WesleyTheGeolien** [comment]
create in that case I'm going to merge the branch

**Pull request merged**
