### PR TITLE
Strat

### PR DESCRIPTION
**Pull request by WesleyTheGeolien**
Hey @kinverarity1 I have added the legend group lith drawing, let me know what you think and if you can think of anything else to add on this branch?

### CODE REVIEW

**Review by kinverarity1 — APPROVED** [review]
This is great! Thank you! I will put something similar in `make_lith` now, so that the "class" is placed in another legend group.

**Comment by kinverarity1** [comment]
I have added two commits:

- Copied your same approach into make_lith so they are now on the legend as well.
- Added a dummy trace in order to get legend group headings

image

**Comment by kinverarity1** [comment]
I can't request you as a reviewer, but if you can take a look and let me know what you think, I think I'm done (for now) with this feature.

**Comment by WesleyTheGeolien** [comment]
@kinverarity1 I'm happy with this, Ill do the merge now

**Pull request merged**
